apiVersion: v1
kind: Service
metadata:
  namespace: funceasy
  name: funceasy-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: funceasy-api
---
apiVersion: v1
kind: Service
metadata:
  namespace: funceasy
  name: funceasy-api-nodeport
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
  selector:
    app: funceasy-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: funceasy
  name: funceasy-api
spec:
  selector:
    matchLabels:
      app: funceasy-api
  template:
    metadata:
      labels:
        app: funceasy-api
    spec:
      containers:
        - image: ziqiancheng/funceasy-api
          name: funceasy-api
          env:
            - name: DATABASE_PASSWORD
              value: administrator
            - name: DATABASE_HOST
              value: funceasy-mysql
            - name: FUNCEASY_API_SERVICE_PORT
              value: "8080"
            - name: GATEWAY_SERVICE_HOST
              value: funceasy-gateway
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: gateway-access
              mountPath: /gateway_access
      volumes:
        - name: gateway-access
          secret:
            secretName: gateway-access